app/forms/file.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, FileField
from wtforms.validators import DataRequired, Length
from flask_wtf.file import FileRequired

class FileForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(min=1, max=50)])
    file = FileField('File', validators=[FileRequired()])
    folder = SelectField('Folder', coerce=str)
    submit = SubmitField('Submit')

app/forms/folder.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length

class FolderForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(min=1, max=50)])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap5
from flask_wtf import CSRFProtect
import secrets


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = secrets.token_hex(16)
    Bootstrap5(app)
    CSRFProtect(app)


    # Register blueprints here
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.files import bp as files_bp
    app.register_blueprint(files_bp, url_prefix='/files')

    from app.folders import bp as folders_bp
    app.register_blueprint(folders_bp, url_prefix='/folders')

   
    return app

app/files/__init__.py
from flask import Blueprint

bp = Blueprint('files', __name__)

from app.files import routes

app/files/routes.py
from app.files import bp
from app.extensions import db
from app.forms.file import FileForm
from werkzeug.utils import secure_filename
from flask import flash, redirect, url_for, render_template, send_file, request
import datetime
import bson
import os

instance_path = os.getcwd() + "/app/data/"
files = db['files']
folders = db['folders']

@bp.route('/')
def index():
    return render_template('files/file.html', files=files.find())

@bp.route('/new/', methods=['GET', 'POST'])
def add():
    try:
        form = FileForm()
        form.folder.choices = [(f['name']) for f in folders.find({})]
        if form.validate_on_submit():
            f = form.file.data
            filename = secure_filename(f.filename)
            f.save(os.path.join(
                instance_path,form.folder.data,filename
            ))
            file = {
                "name": form.name.data,
                "file": filename,
                "path": instance_path + form.folder.data + "/" + filename,
                "created": datetime.datetime.utcnow(),
                "folder": form.folder.data,
                "folder_id": folders.find_one({"name": form.folder.data})['_id']
            }
            files.insert_one(file)
            flash('File created successfully', 'success')
            return redirect(url_for('files.index'))
        return render_template('files/new_file.html', form=form)
    except:
        flash('Error saving data', 'danger')
        return redirect(url_for('files.index'))
    
@bp.route('/edit/<file_id>', methods=['GET', 'POST'])
def edit(file_id):
    try:
        form = FileForm()
        form.folder.choices = [(f['name']) for f in folders.find({})]
        file = files.find_one({"_id": bson.ObjectId(file_id)})
        if form.validate_on_submit():
            os.system("mv " + instance_path + file['folder'] + "/" + file['file'] + " " + instance_path + form.folder.data + "/" + file['file'])
            files.update_one({"_id": bson.ObjectId(file_id)}, {"$set": {"name": form.name.data, "folder": form.folder.data}})
            flash('File updated successfully', 'success')
            return redirect(url_for('files.index'))
        elif request.method == 'GET':
            form.name.data = file['name']
            form.folder.data = file['folder']
        return render_template('files/edit_file.html', form=form, file=file)
    except:
        flash('Error updating data', 'danger')
        return redirect(url_for('files.index'))
    
@bp.route('/delete/<file_id>', methods=['GET', 'POST'])
def delete(file_id):
    try:
        file = files.find_one({"_id": bson.ObjectId(file_id)})
        os.system("rm " + instance_path + file['folder'] + "/" + file['file'])
        files.delete_one({"_id": bson.ObjectId(file_id)})
        flash('File deleted successfully', 'success')
        return redirect(url_for('files.index'))
    except:
        flash('Error deleting data', 'danger')
        return redirect(url_for('files.index'))
    
@bp.route('/download/<file_id>', methods=['GET', 'POST'])
def download(file_id):
    try:
        file = files.find_one({"_id": bson.ObjectId(file_id)})
        flash('File downloaded successfully', 'success')
        return send_file(instance_path + file['folder'] + "/" + file['file'], as_attachment=True)
    except:
        flash('Error downloading file', 'danger')
        return redirect(url_for('files.index'))

app/folders/__init__.py
from flask import Blueprint

bp = Blueprint('folders', __name__)

from app.folders import routes

app/folders/routes.py
from app.folders import bp
from flask import render_template
from app.extensions import db
from app.forms.folder import FolderForm
from flask import flash, redirect, url_for, render_template, request
import datetime
import bson
import os

instance_path = os.getcwd() + "/app/data/"
folders = db['folders']

@bp.route('/')
def index():
    return render_template('folders/folder.html', folders=folders.find())

@bp.route('/new/', methods=['GET', 'POST'])
def add():
    try:
        form = FolderForm()
        if form.validate_on_submit():
            os.system("mkdir -p " + instance_path + form.name.data)
            folder = {
                "name": form.name.data,
                "created": datetime.datetime.utcnow()
            }
            folders.insert_one(folder)
            flash('Folder created successfully', 'success')
            return redirect(url_for('folders.index'))
        return render_template('folders/new_folder.html', form=form)
    except:
        flash('Error saving data', 'danger')
        return redirect(url_for('folders.index'))
    
@bp.route('/edit/<folder_id>', methods=['GET', 'POST'])
def edit(folder_id):
    try:
        form = FolderForm()
        folder = folders.find_one({"_id": bson.ObjectId(folder_id)})
        if form.validate_on_submit():
            os.system("mv " + instance_path + folder['name'] + " " + instance_path + form.name.data)
            folders.update_one({"_id": bson.ObjectId(folder_id)}, {"$set": {"name": form.name.data}})
            flash('Folder updated successfully', 'success')
            return redirect(url_for('folders.index'))
        elif request.method == 'GET':
            form.name.data = folder['name']
        return render_template('folders/edit_folder.html', form=form, folder=folder)

    except: 
        flash('Error updating data', 'danger')
        return redirect(url_for('folders.index'))

@bp.route('/delete/<folder_id>', methods=['GET', 'POST'])
def delete(folder_id):
    try:
        folder = folders.find_one({"_id": bson.ObjectId(folder_id)})
        os.system("rm -rf " + instance_path + folder['name'])
        folders.delete_one({"_id": bson.ObjectId(folder_id)})
        return redirect(url_for('folders.index'))
    except:
        flash('Error deleting data', 'danger')
        return redirect(url_for('folders.index'))

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app.main import bp
from app.extensions import db
from flask import render_template

files=db['files']

@bp.route('/')
def index():
    return render_template('files/file.html', files=files.find())

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

  <title>
  {% block title %}
  {% endblock %}
  </title>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  {{ bootstrap.load_css() }}

  <style>
    
  </style>
</head>
<body>


<!-- Begin alerts -->                
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}

<script>
Swal.fire({
       title:"{{ category.title() }}!",
       // success , error , warning ,info

       text: "{{ message }}",
       // Custom message flashed from your flask routes

       icon: "{{ category }}" == "danger" ? "error" : "{{ category }}"
       // success , error , warning ,info
})
</script>

{% endfor %}
{% endif %}
{% endwith %}

<!-- End alerts -->
{% block content %}
{% endblock %}


{{ bootstrap.load_js() }}
</body>
</html>

app/templates/files/edit_file.html
{% extends 'base.html' %}
{% from 'bootstrap5/form.html' import render_form %}

{% block title %}
Files
{% endblock %}


{% block content %}


<div class="container">
  <div class="row">
    <div class="n_group mt-10 p-5">
      <div class="col-md-10 col-lg-8 mx-lg-auto mx-md-auto d-grid gap-2 d-md-flex justify-content-md-end">
          <a href="{{url_for('main.index')}}"><button class="btn btn-primary" type="button">Back</button></a>
      </div>
  </div>
    <div class="col-md-10 col-lg-8 mx-lg-auto mx-md-auto lead">

      <h3 class="pt-5 pb-2">Edit File </h3>
      <hr/>

      {{ render_form(form) }}

    <span class="text-success lead">{{ message }}</span>

    </div>
  </div>
</div>

{% endblock %}

app/templates/files/file.html
{% extends 'base.html' %} {% from 'bootstrap5/form.html' import render_form %}
{% block title %} Files {% endblock %} {% block content %}
<div class="container mt-10 p-5">
    <div class="row mt-10 p-3">
        <div class="col-md-6 col-lg-6 mx-lg-auto mx-md-auto d-grid gap-2 d-md-flex justify-content-md-start">
            <a href="{{ url_for('folders.index')}}"><button class="btn btn-info" type="submit">Go to Folders</button></a>
        </div>

        <div class="col-md-6 col-lg-6 mx-lg-auto mx-md-auto d-grid gap-2 d-md-flex justify-content-md-end">
            <a href="{{ url_for('files.add')}}"><button class="btn btn-success" type="submit"> + New</button></a>
        </div>
    </div>
    <h3 class="pt-5 pb-2">Files</h3>
    <hr/>

    <table class="table">
        <tr>
            <th>Name</th>
            <th>Folder</th>
            <th>Download</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>

        {% for file in files %}
        <tr class="lead">
            <td>{{ file.name}}</td>
            <td>{{ file.folder }}</td>
            <td><a href="{{url_for('files.download',file_id=file._id)}}"><button class="btn btn-link" type="submit">{{ file.file}}</button></a></td>
            <td><a href="{{url_for('files.edit',file_id=file._id)}}"><button class="btn btn-primary" type="submit">Edit</button></a></td>
            <td><a href="{{url_for('files.delete',file_id=file._id)}}"><button class="btn btn-danger" type="submit">Delete</button></a></td>

        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}

app/templates/files/new_file.html
{% extends 'base.html' %} {% from 'bootstrap5/form.html' import render_form %}
{% block title %} Files {% endblock %} {% block content %}

<div class="container">
  <div class="row">
    <div class="n_group mt-10 p-5">
        <div class="col-md-10 col-lg-8 mx-lg-auto mx-md-auto d-grid gap-2 d-md-flex justify-content-md-end">
            <a href="{{url_for('main.index')}}"><button class="btn btn-primary" type="button">Back</button></a>
        </div>
    </div>
    <div class="col-md-10 col-lg-8 mx-lg-auto mx-md-auto lead">
      <h3 class="pt-5 pb-2">New File</h3>
      <hr />

      {{ render_form(form) }}

      <span class="text-success lead">{{ message }}</span>
    </div>
  </div>
</div>

{% endblock %}

app/templates/folders/edit_folder.html
{% extends 'base.html' %}
{% from 'bootstrap5/form.html' import render_form %}

{% block title %}
Folders
{% endblock %}


{% block content %}


<div class="container">
  <div class="row">
    <div class="n_group mt-10 p-5">
      <div class="col-md-10 col-lg-8 mx-lg-auto mx-md-auto d-grid gap-2 d-md-flex justify-content-md-end">
          <a href="{{url_for('folders.index')}}"><button class="btn btn-primary" type="button">Back</button></a>
      </div>
  </div>
    <div class="col-md-10 col-lg-8 mx-lg-auto mx-md-auto lead">

      <h3 class="pt-5 pb-2">Edit Folder </h3>
      <hr/>

      {{ render_form(form) }}

    <span class="text-success lead">{{ message }}</span>

    </div>
  </div>
</div>

{% endblock %}

app/templates/folders/folder.html
{% extends 'base.html' %} {% from 'bootstrap5/form.html' import render_form %}
{% block title %} Folders {% endblock %} {% block content %}
<div class="container mt-10 p-5">
    <div class="row mt-10 p-3">
        <div class="col-md-6 col-lg-6 mx-lg-auto mx-md-auto d-grid gap-2 d-md-flex justify-content-md-start">
            <a href="{{ url_for('main.index') }}"><button class="btn btn-info" type="submit">Go to Files</button></a>
        </div>

        <div class="col-md-6 col-lg-6 mx-lg-auto mx-md-auto d-grid gap-2 d-md-flex justify-content-md-end">
            <a href="{{ url_for('folders.add') }}"><button class="btn btn-success" type="submit"> + New</button></a>
        </div>
    </div>
    <h3 class="pt-5 pb-2">Folders</h3>
    <hr/>

    <table class="table">
        <tr>
            <th>Name</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>

        {% for folder in folders %}
        <tr class="lead">
            <td>{{ folder.name}}</td>
            <td><a href="{{url_for('folders.edit',folder_id=folder._id)}}"><button class="btn btn-primary" type="submit">Edit</button></a></td>
            <td><a href="{{url_for('folders.delete',folder_id=folder._id)}}"><button class="btn btn-danger" type="submit">Delete</button></a></td>

        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}

app/templates/folders/new_folder.html
{% extends 'base.html' %} {% from 'bootstrap5/form.html' import render_form %}
{% block title %} Folders {% endblock %} {% block content %}

<div class="container">
  <div class="row">
    <div class="n_group mt-10 p-5">
        <div class="col-md-10 col-lg-8 mx-lg-auto mx-md-auto d-grid gap-2 d-md-flex justify-content-md-end">
            <a href="{{url_for('folders.index')}}"><button class="btn btn-primary" type="button">Back</button></a>
        </div>
    </div>
    <div class="col-md-10 col-lg-8 mx-lg-auto mx-md-auto lead">
      <h3 class="pt-5 pb-2">New Folder</h3>
      <hr />

      {{ render_form(form) }}

      <span class="text-success lead">{{ message }}</span>
    </div>
  </div>
</div>

{% endblock %}